<Project>
  <PropertyGroup>
    <BassEmail Condition=" '$(BASS_EMAIL)' != '' ">$(BASS_EMAIL)</BassEmail>
    <BassEmail Condition=" '$(BASS_EMAIL)' == '' ">YOUR_EMAIL_HERE</BassEmail>
    <BassKey Condition=" '$(BASS_KEY)' != '' ">$(BASS_KEY)</BassKey>
    <BassKey Condition=" '$(BASS_KEY)' == '' ">YOUR_KEY_HERE</BassKey>
  </PropertyGroup>
  
  <Target Name="GenerateBassCredentials" BeforeTargets="CoreCompile">
    <PropertyGroup>
      <BassCredentialsFile>$(IntermediateOutputPath)BassCredentials.g.cs</BassCredentialsFile>
    </PropertyGroup>
    <ItemGroup>
      <BassCredentialsLines Include="namespace Panther.Infrastructure.Constants%3B" />
      <BassCredentialsLines Include="public class BassCredentials" />
      <BassCredentialsLines Include="{" />
      <BassCredentialsLines Include="    public const string Email = &quot;$(BassEmail)&quot;%3B" />
      <BassCredentialsLines Include="    public const string Key = &quot;$(BassKey)&quot;%3B" />
      <BassCredentialsLines Include="}" />
    </ItemGroup>
    <WriteLinesToFile File="$(BassCredentialsFile)" Lines="@(BassCredentialsLines)" Overwrite="true" Encoding="UTF-8" />
    <ItemGroup>
      <Compile Include="$(BassCredentialsFile)" />
      <FileWrites Include="$(BassCredentialsFile)" />
    </ItemGroup>
  </Target>
</Project>
