<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <BassNetDllPath Condition=" '$(BASSNET_DLL_PATH)' != '' ">$(BASSNET_DLL_PATH)</BassNetDllPath>
    <BassEmail Condition=" '$(BASS_EMAIL)' != '' ">$(BASS_EMAIL)</BassEmail>
    <BassEmail Condition=" '$(BASS_EMAIL)' == '' ">YOUR_EMAIL_HERE</BassEmail>
    <BassKey Condition=" '$(BASS_KEY)' != '' ">$(BASS_KEY)</BassKey>
    <BassKey Condition=" '$(BASS_KEY)' == '' ">YOUR_KEY_HERE</BassKey>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Panther.Core\Panther.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Bass.Net">
      <HintPath>$(BassNetDllPath)\Bass.Net.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="GenerateBassCredentials" BeforeTargets="CoreCompile">
    <PropertyGroup>
      <BassCredentialsFile>$(IntermediateOutputPath)BassCredentials.g.cs</BassCredentialsFile>
    </PropertyGroup>
    <ItemGroup>
      <BassCredentialsLines Include="namespace Panther.Infrastructure.Constants%3B" />
      <BassCredentialsLines Include="public class BassCredentials" />
      <BassCredentialsLines Include="{" />
      <BassCredentialsLines Include="    public const string Email = &quot;$(BassEmail)&quot;%3B" />
      <BassCredentialsLines Include="    public const string Key = &quot;$(BassKey)&quot;%3B" />
      <BassCredentialsLines Include="}" />
    </ItemGroup>
    <WriteLinesToFile File="$(BassCredentialsFile)" Lines="@(BassCredentialsLines)" Overwrite="true" Encoding="UTF-8" />
    <ItemGroup>
      <Compile Include="$(BassCredentialsFile)" />
      <FileWrites Include="$(BassCredentialsFile)" />
    </ItemGroup>
  </Target>
</Project>